-- Auto-generated from supabase\seed-data\master\csv\grammar_master.csv. Do not edit manually.
insert into public.grammar_master (concept_key, cefr_level, title, short_explanation, concept_type, register, source_note) values
('basic_svo_order', 'A1', 'Basic SVO word order', 'Thai basic statements usually follow subject verb object order.', 'sentence_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('subject_omission_when_clear', 'A1', 'Subject omission when clear', 'Leave out the subject when context already makes it obvious.', 'sentence_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('copula_with_pen', 'A1', 'Copula with เป็น', 'Use เป็น to identify someone or say what something is.', 'sentence_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('adjective_predicate_no_copula', 'A1', 'Adjective predicate without copula', 'Use adjectives directly as the predicate without a verb like ""to be"".', 'sentence_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('noun_modifier_order', 'A1', 'Noun plus modifier order', 'Put most modifiers after the noun they describe.', 'modifier_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('demonstratives_nii_nan', 'A1', 'Demonstratives นี้ and นั้น', 'Use นี้ and นั้น after a noun phrase to mean this and that.', 'modifier_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('interrogative_modifier_nai', 'A1', 'Interrogative ไหน', 'Use ไหน to ask which person place or thing in context.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('personal_pronouns_basic', 'A1', 'Basic personal pronouns', 'Use common beginner-safe pronouns such as ฉัน ผม ดิฉัน คุณ and เรา.', 'pronoun_system', 'formal', 'ai_a1_grammar_master_v3_final'),
('kinship_terms_as_pronouns', 'A1', 'Kinship terms as pronouns', 'Use family-style terms like พี่ น้อง or แม่ as everyday pronouns in context.', 'pronoun_system', 'formal', 'ai_a1_grammar_master_v3_final'),
('reflexive_tua_eeng', 'A1', 'Reflexive with ตัวเอง', 'Use ตัวเอง to refer back to the same person as self.', 'pronoun_system', 'formal', 'ai_a1_grammar_master_v3_final'),
('yes_no_question_mai', 'A1', 'Yes no question with ไหม', 'Add ไหม at the end of a statement to make a yes no question.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('confirmation_question_chai_mai', 'A1', 'Confirmation question with ใช่ไหม', 'Use ใช่ไหม to check or confirm information.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('question_word_arai', 'A1', 'Question word อะไร', 'Use อะไร to ask what.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('question_word_khrai', 'A1', 'Question word ใคร', 'Use ใคร to ask who.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('question_word_thinai', 'A1', 'Question word ที่ไหน', 'Use ที่ไหน to ask where.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('question_word_muearai', 'A1', 'Question word เมื่อไร', 'Use เมื่อไร to ask when.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('question_word_thammai', 'A1', 'Question word ทำไม', 'Use ทำไม to ask why.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('question_word_yangrai', 'A1', 'Question word อย่างไร', 'Use อย่างไร to ask how in a polite beginner-safe way.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('question_word_tao_rai', 'A1', 'Question word เท่าไร', 'Use เท่าไร to ask how much or how many.', 'question_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('negative_mai_general', 'A1', 'General negation with ไม่', 'Use ไม่ before a verb adjective or modal to make it negative.', 'negation', 'formal', 'ai_a1_grammar_master_v3_final'),
('negative_mai_chai', 'A1', 'Negation with ไม่ใช่', 'Use ไม่ใช่ to say something is not the case or not that thing.', 'negation', 'formal', 'ai_a1_grammar_master_v3_final'),
('negative_mai_mii', 'A1', 'Negation with ไม่มี', 'Use ไม่มี to say there is not any or someone does not have something.', 'negation', 'formal', 'ai_a1_grammar_master_v3_final'),
('negative_yang_mai', 'A1', 'Not yet with ยังไม่', 'Use ยังไม่ to say something has not happened yet.', 'negation', 'formal', 'ai_a1_grammar_master_v3_final'),
('negative_mai_khoei', 'A1', 'Never with ไม่เคย', 'Use ไม่เคย to say someone has never done something before.', 'negation', 'formal', 'ai_a1_grammar_master_v3_final'),
('negative_ham', 'A1', 'Prohibition with ห้าม', 'Use ห้าม before a verb to say something is not allowed.', 'negation', 'formal', 'ai_a1_grammar_master_v3_final'),
('existence_and_possession_mii', 'A1', 'Existence and possession with มี', 'Use มี to say something exists or someone has something.', 'verb_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('location_with_yu', 'A1', 'Location with อยู่', 'Use อยู่ to say where someone or something is.', 'location_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('progressive_gamlang', 'A1', 'Progressive with กำลัง', 'Use กำลัง before a verb to show an action is happening now.', 'tense_aspect', 'formal', 'ai_a1_grammar_master_v3_final'),
('ongoing_state_yu', 'A1', 'Ongoing state with อยู่', 'Use อยู่ after some verbs to emphasize an ongoing state or activity.', 'tense_aspect', 'formal', 'ai_a1_grammar_master_v3_final'),
('completion_laew', 'A1', 'Completion with แล้ว', 'Use แล้ว to show an action is completed or a state has changed.', 'tense_aspect', 'formal', 'ai_a1_grammar_master_v3_final'),
('already_yang_question', 'A1', 'Yet in questions with ยัง', 'Use ยัง in questions to ask whether something has happened yet.', 'tense_aspect', 'formal', 'ai_a1_grammar_master_v3_final'),
('experience_khoei', 'A1', 'Past experience with เคย', 'Use เคย before a verb to talk about past experience.', 'tense_aspect', 'formal', 'ai_a1_grammar_master_v3_final'),
('future_intention_ja', 'A1', 'Future intention with จะ', 'Use จะ before a verb for future actions or intentions.', 'tense_aspect', 'formal', 'ai_a1_grammar_master_v3_final'),
('immediate_future_gamlang_ja', 'A1', 'About to with กำลังจะ', 'Use กำลังจะ before a verb to show something is about to happen.', 'tense_aspect', 'formal', 'ai_a1_grammar_master_v3_final'),
('ability_dai', 'A1', 'Ability with ได้', 'Use ได้ with a verb to say someone can do something.', 'verb_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('opportunity_or_permission_dai', 'A1', 'Permission or opportunity with ได้', 'Use ได้ to say someone may do something or had the chance to do it.', 'verb_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('achievement_do_successfully_dai', 'A1', 'Successful completion with ได้', 'Use ได้ after some verbs to show successful result or completion.', 'tense_aspect', 'formal', 'ai_a1_grammar_master_v3_final'),
('inability_or_not_allowed_mai_dai', 'A1', 'Inability or prohibition with ไม่ได้', 'Use ไม่ได้ to say someone cannot do something or is not allowed to.', 'negation', 'formal', 'ai_a1_grammar_master_v3_final'),
('want_yaak', 'A1', 'Want with อยาก', 'Use อยาก before a verb or noun phrase to express wanting.', 'verb_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('need_or_must_tong', 'A1', 'Need or must with ต้อง', 'Use ต้อง before a verb to express necessity or obligation.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('should_khuan', 'A1', 'Should with ควร', 'Use ควร before a verb to give simple advice.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('try_duu', 'A1', 'Try with ดู', 'Use ดู after a verb to suggest trying something in a soft way.', 'verb_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('request_marker_kho', 'A1', 'Request marker ขอ', 'Use ขอ before a verb or noun to make a polite request.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('together_kan', 'A1', 'Together with กัน', 'Use กัน after a verb to show doing something together.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('suggestion_kan_thoe', 'A1', 'Let''s with กันเถอะ', 'Use กันเถอะ to make a friendly suggestion to do something together.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('sentence_softener_noi', 'A1', 'Softening particle หน่อย', 'Use หน่อย to make requests and suggestions sound softer.', 'particle', 'formal', 'ai_a1_grammar_master_v3_final'),
('sentence_softener_na', 'A1', 'Softening particle นะ', 'Use นะ to soften a sentence or make it sound more friendly.', 'particle', 'formal', 'ai_a1_grammar_master_v3_final'),
('emphasis_particle_si', 'A1', 'Emphasis particle สิ', 'Use สิ in simple speech to add light emphasis or encouragement.', 'particle', 'informal', 'ai_a1_grammar_master_v3_final'),
('polite_particles_khrab_kha', 'A1', 'Polite sentence-final particles', 'Use ครับ and ค่ะ to make speech polite and socially appropriate.', 'politeness', 'formal', 'ai_a1_grammar_master_v3_final'),
('coordination_kap', 'A1', 'Linking with กับ', 'Use กับ to link nouns or show with together with someone.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('coordination_lae', 'A1', 'Linking with และ', 'Use และ to connect nouns or clauses in more formal Thai.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('alternative_rue', 'A1', 'Alternative with หรือ', 'Use หรือ to mean or between choices.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('reason_phro_wa', 'A1', 'Reason with เพราะว่า', 'Use เพราะว่า to introduce a reason.', 'functional_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('result_ko_loei', 'A1', 'Result with ก็เลย', 'Use ก็เลย to connect a reason and result in everyday Thai.', 'functional_expression', 'informal', 'ai_a1_grammar_master_v3_final'),
('sequence_particle_ko', 'A1', 'Sequence particle ก็', 'Use ก็ to continue the sentence with then so or in that case depending on context.', 'particle', 'formal', 'ai_a1_grammar_master_v3_final'),
('addition_duai', 'A1', 'Addition with ด้วย', 'Use ด้วย to add the meaning of also or too.', 'particle', 'formal', 'ai_a1_grammar_master_v3_final'),
('emphasis_eeng', 'A1', 'Emphasis with เอง', 'Use เอง to emphasize self or by oneself.', 'particle', 'formal', 'ai_a1_grammar_master_v3_final'),
('basic_classifiers_counting', 'A1', 'Basic classifiers after numbers', 'Use a classifier after a number when counting nouns.', 'classifier_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('classifier_with_demonstratives', 'A1', 'Classifier with demonstratives', 'Use the classifier before นี้ นั้น or โน้น when pointing to nouns.', 'classifier_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('classifier_with_interrogatives', 'A1', 'Classifier with interrogatives', 'Use the classifier in questions like คนไหน or อันไหน when asking which one.', 'classifier_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('noun_number_classifier_order', 'A1', 'Noun plus number plus classifier order', 'Count nouns with the pattern noun plus number plus classifier.', 'quantity', 'formal', 'ai_a1_grammar_master_v3_final'),
('quantity_words_many_few', 'A1', 'Quantity words มาก and น้อย', 'Use common quantity words to express more less or few.', 'quantity', 'formal', 'ai_a1_grammar_master_v3_final'),
('approximation_pramaan', 'A1', 'Approximation with ประมาณ', 'Use ประมาณ to give an approximate number time or amount.', 'quantity', 'formal', 'ai_a1_grammar_master_v3_final'),
('all_thangmot', 'A1', 'All with ทั้งหมด', 'Use ทั้งหมด to refer to the whole amount or all items.', 'quantity', 'formal', 'ai_a1_grammar_master_v3_final'),
('some_baang', 'A1', 'Some with บาง', 'Use บาง to refer to some people things or cases but not all.', 'quantity', 'formal', 'ai_a1_grammar_master_v3_final'),
('each_every_thuk', 'A1', 'Each or every with ทุก', 'Use ทุก before a time word or noun to mean every or each.', 'quantity', 'formal', 'ai_a1_grammar_master_v3_final'),
('comparative_kwa', 'A1', 'Comparative with กว่า', 'Use กว่า to compare two things and show one has more of a quality.', 'comparison', 'formal', 'ai_a1_grammar_master_v3_final'),
('superlative_thii_sut', 'A1', 'Superlative with ที่สุด', 'Use ที่สุด to show the highest degree.', 'comparison', 'formal', 'ai_a1_grammar_master_v3_final'),
('equality_thao_kap', 'A1', 'Equality with เท่ากับ', 'Use เท่ากับ to say two things are equal in amount or degree.', 'comparison', 'formal', 'ai_a1_grammar_master_v3_final'),
('intensifier_mak', 'A1', 'Intensifier มาก', 'Use มาก after an adjective or verb to mean very or a lot.', 'modifier_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('degree_nit_noi', 'A1', 'Degree with นิดหน่อย', 'Use นิดหน่อย to show a small amount or low degree.', 'modifier_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('location_marker_thii', 'A1', 'Location marker ที่', 'Use ที่ before a place to mark location or destination in simple patterns.', 'location_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('movement_pai', 'A1', 'Movement with ไป', 'Use ไป with a place or verb to show movement away or going to do something.', 'location_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('movement_maa', 'A1', 'Movement with มา', 'Use มา to show movement toward the speaker or reference point.', 'location_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('source_jaak', 'A1', 'Source with จาก', 'Use จาก to show where someone or something comes from.', 'location_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('arrival_thueng', 'A1', 'Arrival with ถึง', 'Use ถึง for reaching a place time or endpoint.', 'location_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('position_words_basic', 'A1', 'Basic position words', 'Use simple words such as บน ใต้ ใน หน้า หลัง and ข้าง to describe position.', 'location_pattern', 'formal', 'ai_a1_grammar_master_v3_final'),
('time_reference_basic', 'A1', 'Basic time reference words', 'Use words like วันนี้ พรุ่งนี้ and เมื่อวาน to place events in time.', 'time_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('days_of_week_basic', 'A1', 'Days of the week', 'Use day names to say when something happens.', 'time_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('clock_time_basic', 'A1', 'Basic clock time expressions', 'Use time expressions with numbers to say what time it is.', 'time_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('time_sequence_before_after', 'A1', 'Before and after with ก่อน and หลัง', 'Use ก่อน and หลัง to place events in sequence.', 'time_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('time_duration_nan', 'A1', 'Duration with นาน', 'Use นาน to talk about how long something lasts.', 'time_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('frequency_basic', 'A1', 'Basic frequency expressions', 'Use common words like บ่อย and every day to say how often something happens.', 'time_expression', 'formal', 'ai_a1_grammar_master_v3_final'),
('adjective_after_noun', 'A1', 'Adjective after noun', 'In Thai adjectives follow the noun they describe using the pattern Noun + Adjective in both simple descriptions and conversational sentences.', 'modifier_pattern', 'formal', 'ai_a1_grammar_master_v3_final');
