-- Auto-generated from supabase\seed-data\pattern_master.csv. Do not edit manually.
insert into public.pattern_master (pattern_key, cefr_level, title, pattern_formula, short_explanation, pattern_type, register, fixedness_level, is_productive, source_note) values
('mai_verb', 'A1', 'Not do', 'ไม่ + VERB', 'Negates an action or state.', 'negation_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('yang_mai_verb', 'A1', 'Not yet do', 'ยังไม่ + VERB', 'Says something has not happened yet.', 'negation_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('mai_chai_noun', 'A1', 'Not be noun', 'ไม่ใช่ + NOUN', 'Says something is not a person or thing.', 'negation_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('mai_mi_noun', 'A1', 'Not have noun', 'ไม่มี + NOUN', 'Says something does not exist or is not available.', 'negation_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('mai_dai_verb', 'A1', 'Not able to do', 'ไม่ได้ + VERB', 'Says someone cannot do or did not do something in basic contexts.', 'ability_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('ya_verb', 'A1', 'Do not do', 'อย่า + VERB', 'Tells someone not to do something.', 'request_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('yak_verb', 'A1', 'Want to do', 'อยาก + VERB', 'Expresses wanting to do something.', 'preference_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('yaak_dai_noun', 'A1', 'Want noun', 'อยากได้ + NOUN', 'Expresses wanting an item or thing.', 'preference_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('chop_noun', 'A1', 'Like noun', 'ชอบ + NOUN', 'Expresses liking a thing or category.', 'preference_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('chop_verb', 'A1', 'Like doing', 'ชอบ + VERB', 'Expresses liking an activity.', 'preference_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('mai_chop_noun', 'A1', 'Do not like noun', 'ไม่ชอบ + NOUN', 'Expresses not liking a thing.', 'preference_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('mai_chop_verb', 'A1', 'Do not like doing', 'ไม่ชอบ + VERB', 'Expresses not liking an activity.', 'preference_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('kho_verb_dai_mai', 'A1', 'May I do', 'ขอ + VERB + ได้ไหม', 'Asks politely for permission to do something.', 'permission_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('kho_noun_noi', 'A1', 'Please give noun', 'ขอ + NOUN + หน่อย', 'Politely asks for an item.', 'request_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('kho_verb_noi', 'A1', 'Please do', 'ขอ + VERB + หน่อย', 'Politely asks someone to do something.', 'request_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('chuai_verb_noi', 'A1', 'Help do please', 'ช่วย + VERB + หน่อย', 'Softens a request for help or action.', 'request_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('verb_hai_person', 'A1', 'Do for someone', 'VERB + ให้ + PERSON', 'Shows the action is done for someone.', 'result_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('verb_duai_dai_mai', 'A1', 'Can join do', 'VERB + ด้วย + ได้ไหม', 'Asks to join or take part politely.', 'permission_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('verb_duai', 'A1', 'Do too', 'VERB + ด้วย', 'Adds the meaning of also or too.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('ao_noun', 'A1', 'Take or want noun', 'เอา + NOUN', 'Used to choose or ask for something in simple situations.', 'sentence_frame', 'informal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('ao_pen_noun', 'A1', 'Choose as noun', 'เอาเป็น + NOUN', 'Used to select one option in a simple way.', 'sentence_frame', 'informal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('mi_noun', 'A1', 'Have noun', 'มี + NOUN', 'Says someone has something or something exists.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('mi_noun_mai', 'A1', 'Have noun question', 'มี + NOUN + ไหม', 'Asks whether something exists or is available.', 'question_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('pen_noun', 'A1', 'Be noun', 'เป็น + NOUN', 'Identifies a person or thing by category or role.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('verb_pen', 'A1', 'Know how to do', 'VERB + เป็น', 'Shows someone knows how to do a learned skill.', 'ability_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('dai_verb', 'A1', 'Can do', 'ได้ + VERB', 'Shows ability or possibility in basic use.', 'ability_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('verb_dai_mai', 'A1', 'Can do question', 'VERB + ได้ไหม', 'Asks if something can be done.', 'ability_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('verb_mai_dai', 'A1', 'Cannot do', 'VERB + ไม่ได้', 'Says something cannot be done.', 'ability_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('tong_verb', 'A1', 'Must do', 'ต้อง + VERB', 'Expresses necessity or obligation.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('tong_verb_mai', 'A1', 'Need to do question', 'ต้อง + VERB + ไหม', 'Asks whether something is necessary.', 'question_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('yak_verb_mai', 'A1', 'Want to do question', 'อยาก + VERB + ไหม', 'Asks whether someone wants to do something.', 'question_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('yaak_dai_noun_mai', 'A1', 'Want noun question', 'อยากได้ + NOUN + ไหม', 'Asks whether someone wants an item or thing.', 'question_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('statement_chai_mai', 'A1', 'Statement check', 'STATEMENT + ใช่ไหม', 'Checks whether a statement is correct.', 'question_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('statement_reu_plao', 'A1', 'Statement or not', 'STATEMENT + หรือเปล่า', 'Turns a statement into a yes or no question.', 'question_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('statement_mai', 'A1', 'Question with mai', 'STATEMENT + ไหม', 'Makes a simple yes or no question.', 'question_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('thammai_verb', 'A1', 'Why do', 'ทำไม + VERB', 'Asks for a reason for an action.', 'question_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('noun_arai', 'A1', 'What noun', 'NOUN + อะไร', 'Asks what person or thing is meant.', 'question_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('khrai_pen_noun', 'A1', 'Who is this person', 'ใคร + เป็น + NOUN', 'Asks who a person is by role or identity.', 'question_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('yuu_thi_nai', 'A1', 'Be where', 'อยู่ที่ไหน', 'Asks where someone or something is.', 'location_frame', 'formal', 'fixed', false, 'ai_a1_pattern_master_v3_final'),
('pai_thi_nai', 'A1', 'Go where', 'ไปที่ไหน', 'Asks where someone is going.', 'location_frame', 'formal', 'fixed', false, 'ai_a1_pattern_master_v3_final'),
('maa_muea_rai', 'A1', 'Come when', 'มาเมื่อไร', 'Asks when someone comes or came.', 'time_frame', 'formal', 'fixed', false, 'ai_a1_pattern_master_v3_final'),
('verb_muea_rai', 'A1', 'Do when', 'VERB + เมื่อไร', 'Asks when an action happens.', 'time_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('quantity_gee_classifier', 'A1', 'How many items', '... กี่ + CLASSIFIER', 'Asks for quantity with a classifier.', 'quantity_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('price_thao_rai', 'A1', 'How much price', '... เท่าไร', 'Asks for price or amount.', 'quantity_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('noun_number_classifier', 'A1', 'Noun with number', 'NOUN + NUMBER + CLASSIFIER', 'Counts things with a classifier.', 'classifier_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('noun_classifier_ni', 'A1', 'This classifier noun', 'NOUN + CLASSIFIER + นี้', 'Points to this specific item.', 'classifier_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('noun_classifier_nan', 'A1', 'That classifier noun', 'NOUN + CLASSIFIER + นั้น', 'Points to that specific item.', 'classifier_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('noun_number_classifier_ni', 'A1', 'This many noun', 'NOUN + NUMBER + CLASSIFIER + นี้', 'Refers to this specific number of items.', 'classifier_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('mi_gee_classifier', 'A1', 'Have how many', 'มี + ... กี่ + CLASSIFIER', 'Asks how many items there are.', 'quantity_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('thi_place', 'A1', 'At place', 'ที่ + PLACE', 'Marks a place in simple phrases.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('yuu_thi_place', 'A1', 'Be at place', 'อยู่ที่ + PLACE', 'Says where someone or something is.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('pai_place', 'A1', 'Go to place', 'ไป + PLACE', 'Shows movement to a place.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('ma_jak_place', 'A1', 'Come from place', 'มา + จาก + PLACE', 'Shows origin or starting place.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('jak_place', 'A1', 'From place', 'จาก + PLACE', 'Marks where something or someone comes from.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('nai_place', 'A1', 'In place', 'ใน + PLACE', 'Marks location inside a place.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('bon_noun', 'A1', 'On noun', 'บน + NOUN', 'Marks location on top of something.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('glai_place', 'A1', 'Near place', 'ใกล้ + PLACE', 'Says something is near a place.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('klai_jak_place', 'A1', 'Far from place', 'ไกลจาก + PLACE', 'Says something is far from a place.', 'location_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('wela_time', 'A1', 'At time', 'เวลา + TIME', 'Gives a clock time.', 'time_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('ton_time', 'A1', 'At time period', 'ตอน + TIME', 'Places an action in a part of the day or period.', 'time_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('time_ni', 'A1', 'This time', 'TIME + นี้', 'Refers to this time or period.', 'time_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('ik_time', 'A1', 'Another time later', 'อีก + TIME', 'Means another amount of time or later time.', 'time_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('verb_ton_time', 'A1', 'Do at time period', 'VERB + ตอน + TIME', 'Says when an action happens.', 'time_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('verb_wela_time', 'A1', 'Do at clock time', 'VERB + เวลา + TIME', 'Says an action happens at a specific time.', 'time_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('verb_laeo', 'A1', 'Already do', 'VERB + แล้ว', 'Shows an action is completed already.', 'result_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('kamlang_verb', 'A1', 'Be doing', 'กำลัง + VERB', 'Shows an action in progress.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('kamlang_verb_yu', 'A1', 'Be doing now', 'กำลัง + VERB + อยู่', 'Strongly marks an action as ongoing.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('ja_verb', 'A1', 'Will do', 'จะ + VERB', 'Shows future intention or near future.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('ja_pai_place', 'A1', 'Will go to place', 'จะไป + PLACE', 'Expresses planned movement to a place.', 'location_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('adjective_mak', 'A1', 'Very adjective', 'ADJECTIVE + มาก', 'Intensifies an adjective to mean very.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('adjective_noi', 'A1', 'A little adjective', 'ADJECTIVE + นิดหน่อย', 'Softens an adjective to mean a little.', 'sentence_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('softener_noi', 'A1', 'Softener noi', '... หน่อย', 'Softens requests or suggestions politely.', 'politeness_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('adjective_kwa', 'A1', 'More adjective', 'ADJECTIVE + กว่า', 'Makes a simple comparison.', 'comparison_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('adjective_thi_sut', 'A1', 'Most adjective', 'ADJECTIVE + ที่สุด', 'Forms a basic superlative.', 'comparison_frame', 'formal', 'productive', true, 'ai_a1_pattern_master_v3_final'),
('statement_di_mai', 'A1', 'Would it be good', 'STATEMENT + ดีไหม', 'Makes a soft suggestion.', 'request_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final'),
('question_answer_polite', 'A1', 'Question and polite answer', 'A: ... ไหม / B: ... ครับ/ค่ะ', 'Models a basic yes or no exchange with polite particles.', 'response_frame', 'formal', 'semi_fixed', true, 'ai_a1_pattern_master_v3_final');
